package httpapi

// Presentation copy and defaults preserved from the settings UI; model policy lives in Go.
var llmSettingsControlTemplates = map[string]llmReasoningControls{
	"risu": {
		Mode: "risu_reasoning", ShowEffort: true, EffortLabel: "추론 강도",
		EffortHint: "선택한 플러그인 모델에 추론 강도를 전달합니다. 그 플러그인이 받지 않으면 반영되지 않습니다.",
		ShowBudget: true, BudgetLabel: "추론 토큰 예산",
		BudgetHint:    "선택한 플러그인 모델에 추론 토큰 예산을 전달합니다.",
		GuideModeText: "RisuAI 플러그인 모델 · reasoningEffort / thinkingTokens",
	},
	"glm_required": {
		Mode: "glm_reasoning_effort", ShowEffort: true, EffortLabel: "추론 강도",
		EffortHint:    "GLM 5.3 · 항상 추론하며 low / high / max를 지원합니다.",
		GuideModeText: "GLM 5.3 · thinking enabled + reasoning_effort",
	},
	"kimi_toggle": {
		Mode: "kimi_toggle", ShowEffort: true, EffortLabel: "추론 모드",
		EffortHint: "Kimi K2.5·K2.6 · 켜기 / 끄기", GuideModeText: "Kimi · thinking.type",
	},
	"kimi_always": {
		Mode: "kimi_always", EffortLabel: "추론 모드",
		GuideModeText: "Kimi K2.7 Code · 항상 추론 · 강도 조절 없음",
	},
	"kimi_effort": {
		Mode: "kimi_reasoning_effort", ShowEffort: true, EffortLabel: "추론 강도",
		EffortHint:    "Kimi K3 · 항상 추론하며 low / high / max를 지원합니다.",
		GuideModeText: "Kimi K3 · reasoning_effort",
	},
	"conflict": {
		Mode:          "unsupported",
		ShowEffort:    false,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "선택한 provider와 공식 endpoint가 서로 달라 추론 필드를 전달하지 않습니다.",
	},
	"ollama_glm_effort": {
		Mode:          "ollama_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "GLM 5.2 이상은 Ollama OpenAI 호환 규약에서 끄기/High만 전달합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델/전송 규약: GLM 5.2+ effort → Ollama reasoning_effort",
	},
	"ollama_glm_toggle": {
		Mode:          "ollama_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Toggle",
		EffortHint:    "GLM 5.1 이하는 thinking 켜기/끄기만 선택하고 Ollama 전송값으로 변환합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델/전송 규약: GLM toggle → Ollama reasoning_effort",
	},
	"ollama": {
		Mode:          "ollama_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "Ollama endpoint 규약에 맞춰 none/low/medium/high만 전달합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 전송 규약: Ollama OpenAI 호환 reasoning_effort",
	},
	"gateway": {
		Mode:          "gateway_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "선택한 gateway의 전송 형식으로 변환해 전달합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 전송 규약: llmgateway reasoning",
	},
	"glm_effort": {
		Mode:          "glm_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "GLM 5.2 이상은 none/high/max를 사용합니다. low/medium은 high, xhigh는 max로 정규화됩니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델 감지: GLM 5.2+ thinking.type + reasoning_effort",
	},
	"glm_toggle": {
		Mode:          "glm_toggle",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Toggle",
		EffortHint:    "GLM 5.1 이하는 enable/disable thinking toggle을 사용합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델 감지: GLM thinking.type",
	},
	"deepseek": {
		Mode:          "deepseek_v4_reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "DeepSeek V4는 provider가 지원하는 none/low/high/max를 사용합니다. 별도 추론 토큰 예산은 전달하지 않습니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 전송 규약: DeepSeek V4 thinking.type + reasoning_effort",
	},
	"unsupported_gemini": {
		Mode:          "unsupported",
		ShowEffort:    false,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 Gemini 모델에서 확인된 추론 제어 형식이 없어 추론 필드를 전달하지 않습니다.",
	},
	"gemini_level": {
		Mode:          "thinking_level",
		ShowEffort:    true,
		EffortLabel:   "Thinking Level",
		EffortHint:    "none은 thinking level을 전달하지 않습니다. Gemini 3 계열은 minimal/low/medium/high thinking level을 사용합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "Gemini 3 계열에서는 token budget 대신 thinking level을 사용합니다.",
		GuideModeText: "현재 모델 감지: Gemini 3 thinkingLevel",
	},
	"gemini_budget": {
		Mode:          "thinking_budget",
		ShowEffort:    false,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "",
		ShowBudget:    true,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "Gemini 2.5 계열은 thinkingBudget(토큰 예산)을 사용합니다.",
		GuideModeText: "현재 모델 감지: Gemini 2.5 thinkingBudget",
	},
	"claude_adaptive": {
		Mode:          "claude_adaptive",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "Claude 4.6 이상은 adaptive thinking과 effort를 사용합니다. 숫자 budget은 전달하지 않습니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델 감지: Claude adaptive thinking + effort",
	},
	"claude_budget": {
		Mode:          "claude_manual_budget",
		ShowEffort:    false,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "",
		ShowBudget:    true,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "Claude 3.7~4.5는 thinking budget_tokens를 사용하며 max completion보다 작아야 합니다.",
		GuideModeText: "현재 모델 감지: Claude manual thinking budget",
	},
	"gpt": {
		Mode:          "reasoning_effort",
		ShowEffort:    true,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "선택한 OpenAI 모델 세대가 지원하는 reasoning_effort만 표시합니다.",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델 감지: reasoning effort",
	},
	"unsupported": {
		Mode:          "unsupported",
		ShowEffort:    false,
		EffortLabel:   "Reasoning Effort",
		EffortHint:    "",
		ShowBudget:    false,
		BudgetLabel:   "Reasoning Budget Tokens",
		BudgetHint:    "",
		GuideModeText: "현재 모델에서 확인된 추론 제어 형식이 없어 추론 필드를 전달하지 않습니다.",
	},
}
var llmSettingsPresetGuides = map[string]llmReasoningPreset{
	"kimi_toggle": {Label: "Kimi K2.5 / K2.6", Effort: "enable", Hint: "추론 켜기/끄기를 지원합니다."},
	"kimi_always": {Label: "Kimi K2.7 Code", Hint: "항상 추론하며 강도 조절은 지원하지 않습니다."},
	"kimi_effort": {Label: "Kimi K3", Effort: "max", Hint: "low/high/max를 지원합니다."},
	"gpt": {
		Label:           "GPT",
		Effort:          "medium",
		BudgetTokens:    0,
		GlmThinkingType: "disabled",
		Hint:            "OpenAI reasoning 문서 기준 effort(low/medium/high 등)를 주로 쓰며, output token 상한을 함께 관리합니다.",
	},
	"gemini": {
		Label:           "Gemini",
		Effort:          "high",
		ThinkingLevel:   "high",
		BudgetTokens:    1024,
		GlmThinkingType: "disabled",
		Hint:            "Google Gemini thinking 문서 기준 2.5 계열은 thinkingBudget(토큰 예산), 3 계열은 thinkingLevel이 핵심입니다.",
	},
	"claude": {
		Label:           "Claude",
		Effort:          "high",
		BudgetTokens:    2048,
		GlmThinkingType: "disabled",
		Hint:            "Anthropic extended thinking 문서 기준 thinking budget_tokens(또는 adaptive thinking)가 핵심입니다.",
	},
	"glm": {
		Label:           "GLM",
		Effort:          "enable",
		BudgetTokens:    0,
		GlmThinkingType: "enabled",
		Hint:            "GLM 5.2 이상은 추론 강도를 지원하고, 이전 GLM은 thinking.type enabled/disabled 토글을 사용합니다.",
	},
	"deepseek_v4": {
		Label:           "DeepSeek V4",
		Effort:          "high",
		BudgetTokens:    0,
		GlmThinkingType: "disabled",
		Hint:            "DeepSeek V4는 provider가 지원하는 low/high/max 추론 강도를 사용하며 별도 추론 토큰 예산을 사용하지 않습니다.",
	},
	"custom": {
		Label:           "Custom",
		Effort:          "none",
		BudgetTokens:    0,
		GlmThinkingType: "disabled",
		Hint:            "모델 계약이 확인되지 않으면 추론 필드를 자동으로 보내지 않습니다. 고급 필드는 Extra Body JSON에서만 명시합니다.",
	},
	"none": {
		Label:           "Auto",
		Effort:          "none",
		BudgetTokens:    0,
		GlmThinkingType: "disabled",
		Hint:            "입력된 모델에서 확인된 추론 제어 형식이 없으면 추론 필드를 보내지 않습니다.",
	},
}
